# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='Locations',
        ),
    ]
