# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180921_2323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedlocations',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='usercontacts',
            unique_together=set([]),
        ),
    ]
