# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180922_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
