# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_usercontacts_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontacts',
            name='phone_number',
        ),
    ]
