# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_usercontacts_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontacts',
            name='number',
            field=models.IntegerField(default='none', max_length=12, null=True),
        ),
    ]
